services:
  data-storage:
    build:
      context: .
      dockerfile: services/data-storage/Dockerfile
    container_name: data-storage
    volumes:
      - db-data:/app/database
    networks:
      - ventes-network
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  script-executor:
    build:
      context: .
      dockerfile: services/script-executor/Dockerfile
    container_name: script-executor
    volumes:
      - db-data:/app/database
      - ./data:/app/data
      - ./results:/app/results
    depends_on:
      data-storage:
        condition: service_healthy
    networks:
      - ventes-network

volumes:
  db-data:

networks:
  ventes-network:
    driver: bridge
    name: ventes-network
