version: '3.8'

services:
  # Service de stockage de données avec SQLite
  data-storage:
    build:
      context: .
      dockerfile: services/data-storage/Dockerfile
    container_name: data-storage
    volumes:
      - db-data:/app/database
      - ./init-scripts:/app/init-scripts:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlite3", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - ventes-network

  # Service d'exécution des scripts
  script-executor:
    build:
      context: .
      dockerfile: services/script-executor/Dockerfile
    container_name: script-executor
    volumes:
      - db-data:/app/database
      - ./data:/app/data
      - ./results:/app/results
      - ./.env:/app/.env:ro
    depends_on:
      data-storage:
        condition: service_healthy
    env_file:
      - ./.env
    #restart: unless-stopped
    networks:
      - ventes-network

volumes:
  db-data:
    name: db-data

networks:
  ventes-network:
    driver: bridge
    name: ventes-network